### ISSUE TITLE
1st time account creation doesn't work when already logged somewhere using cas

### ISSUE THREAD

**Issue by Sylvain38ria** [univlorraine/limesurvey-cas#13] opened 2018-09-04 10:53 UTC
Hi,

I use limesurvey version 3.14.7+180827 and i have the following problem:

- If i open my browser and then go to my survey site authenticating myself by cas for the first time, it works perfectly
but...
- If I'm already logged using cas on another app and go to my survey site for the first time, it doesn't work. I'm well connected but I have no rights. By looking in the database, no new data is registered in lime_users and lime_permissions.

Any suggestions to solve this problem?

Regards,
Sylvain

**Comment by goyome** [comment] 2018-09-05 08:06
Hi,

If no data is registered in lime_users, you shouldn't be allowed to connect to LS admin.

By the way, the origin can't be the connection to another app through CAS. CAS is the central point and the behavior of authentication doesn't change depending on a previous authentication.
The only difference will be that you won't see the authentication form as you are already authenticated.

You should check again that everything is going well when you create a new account on the first connection. (your first case)
Then delete the account, and redo the exact same action after having previously authenticating to CAS. You should have the exact same result.

Regards

**Comment by ghost** [comment] 2018-09-14 07:14
Hi,

The problem seems to come from my side. Your plugin works correctly. I'm going to look at what's wrong with me. Thank you. 
Thank you.

**Comment by goyome** [comment] 2018-09-14 08:42
Thanks for your reply.
Since the problem is not from the code, I'll close this issue.

**Closed as completed by goyome** 2018-09-14 08:42 UTC
